//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass2mvc4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public book()
        {
            this.saleRecords = new HashSet<saleRecord>();
        }
    
        public int ISBN { get; set; }
        public string bookName { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
        public Nullable<int> noInStock { get; set; }
    
        public virtual ICollection<saleRecord> saleRecords { get; set; }
    }
}
